package tech.vvp.vvp.client.model;

import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity;
import net.minecraft.util.Mth;
import tech.vvp.vvp.entity.vehicle.CV90Entity;

public class CV90Model extends VvpVehicleModel<CV90Entity> {

    @Override
    public boolean hideForTurretControllerWhileZooming() {
        return true;
    }

    // Generated by Track Builder - 71 tracks
// Pivot: [0, 14.50, 42.00]

    private static final int TRACK_COUNT = 71;
    private static final int MAX_IDX = 71;
    private static final float[][] KEYFRAMES = {
            {-179.12f, 14.50f, 42.00f},
            {143.02f, 13.55f, 44.77f},
            {105.04f, 11.10f, 46.36f},
            {67.06f, 8.18f, 46.12f},
            {29.08f, 6.03f, 44.12f},
            {24.81f, 4.84f, 41.40f},
            {24.81f, 3.58f, 38.69f},
            {24.81f, 2.33f, 35.99f},
            {24.81f, 1.08f, 33.28f},
            {0.00f, 0.50f, 30.40f},
            {0.00f, 0.50f, 27.42f},
            {0.00f, 0.50f, 24.44f},
            {0.00f, 0.50f, 21.46f},
            {0.00f, 0.50f, 18.48f},
            {0.00f, 0.50f, 15.50f},
            {0.00f, 0.50f, 12.52f},
            {0.00f, 0.50f, 9.54f},
            {0.00f, 0.50f, 6.56f},
            {0.00f, 0.50f, 3.57f},
            {0.00f, 0.50f, 0.59f},
            {0.00f, 0.50f, -2.39f},
            {0.00f, 0.50f, -5.37f},
            {0.00f, 0.50f, -8.35f},
            {0.00f, 0.50f, -11.33f},
            {0.00f, 0.50f, -14.31f},
            {0.00f, 0.50f, -17.29f},
            {0.00f, 0.50f, -20.27f},
            {0.00f, 0.50f, -23.25f},
            {0.00f, 0.50f, -26.23f},
            {0.00f, 0.50f, -29.21f},
            {0.00f, 0.50f, -32.20f},
            {-2.04f, 0.50f, -35.18f},
            {-28.74f, 1.42f, -37.97f},
            {-28.74f, 2.85f, -40.58f},
            {-28.74f, 4.28f, -43.20f},
            {-28.74f, 5.72f, -45.81f},
            {-28.74f, 7.15f, -48.43f},
            {-41.67f, 8.64f, -50.99f},
            {-79.49f, 11.19f, -52.43f},
            {-117.30f, 14.09f, -51.99f},
            {-155.12f, 16.10f, -49.86f},
            {172.95f, 16.28f, -46.96f},
            {169.79f, 15.74f, -44.02f},
            {170.28f, 15.22f, -41.09f},
            {170.92f, 14.73f, -38.15f},
            {171.56f, 14.27f, -35.20f},
            {172.20f, 13.84f, -32.25f},
            {172.85f, 13.45f, -29.30f},
            {173.50f, 13.10f, -26.34f},
            {174.15f, 12.78f, -23.38f},
            {174.80f, 12.49f, -20.41f},
            {175.45f, 12.24f, -17.44f},
            {176.10f, 12.02f, -14.47f},
            {176.76f, 11.84f, -11.49f},
            {177.41f, 11.69f, -8.51f},
            {178.07f, 11.57f, -5.53f},
            {178.73f, 11.49f, -2.55f},
            {179.38f, 11.45f, 0.43f},
            {-179.96f, 11.44f, 3.41f},
            {-179.30f, 11.47f, 6.39f},
            {-178.64f, 11.53f, 9.37f},
            {-177.99f, 11.63f, 12.35f},
            {-177.33f, 11.76f, 15.32f},
            {-176.68f, 11.93f, 18.30f},
            {-176.02f, 12.13f, 21.28f},
            {-175.37f, 12.36f, 24.25f},
            {-174.72f, 12.63f, 27.22f},
            {-174.07f, 12.94f, 30.18f},
            {-173.42f, 13.28f, 33.14f},
            {-172.77f, 13.65f, 36.10f},
            {-172.12f, 14.06f, 39.05f},
            {-179.12f, 14.50f, 42.00f}
    };

    private static final float START_Y = 14.50f;
    private static final float START_Z = 42.00f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

//    @Override
//    public int getDefaultWrapRange(VehicleEntity vehicle) {
//        return TRACK_COUNT * 2;
//    }
}